### ISSUE TITLE
FEATURE REQUEST: REALLY Custom sound - changeable programmatically!  (+added code for possible fix)

### ISSUE THREAD

**Issue by b3nnee** [Obsessive/nativescript-custom-local-notifications#1]
It will be super nice to have the ability to play custom sound specified via code when the notification is created in {N}. 

I believe a modification to the localnotifications.jar file should fix this:

Specifically in the file  NotificationRestoreReceiver.java

On line 55:
`NotificationCompat.Builder builder = new NotificationCompat.Builder(context).setDefaults(0).setContentTitle((CharSequence)options.optString("title")).setContentText((CharSequence)options.optString("body")).setSmallIcon(options.optInt("icon")).setAutoCancel(true).setSound(options.has("sound") ? Uri.parse((String)("android.resource://" + context.getPackageName() + "/raw/" + options.optString("sound"))) : Uri.parse((String)("android.resource://" + context.getPackageName() + "/raw/notify")) ).setNumber(options.optInt("badge")).setTicker((CharSequence)options.optString("ticker"));`

Kindly rebuild the file (my environment is not setup for it at the moment) with this edit and send to me, I will be happy to test!

Cheers.

**Comment by Obsessive** [comment]
Thank @b3nnee ! 
I'll build and upload it in some time :)

**Comment by Obsessive** [comment]
Hi @b3nnee ,
Please test and confirm this .

**Comment by b3nnee** [comment]
Will do, thanks, cheers.

Best regards,

Ben

**Comment by b3nnee** [comment]
Hi @Obsessive ,

Code I gave above was incomplete, as I didn't want to disturb you, I was able to build my own jar and test properly.

Two files need to be modified:

NotificationPublisher.java
NotificationRestoreReceiver.java

I attached them, fixed. 

To use now simply copy all the notification sounds to be used to raw folder
then add the sound when notifications are scheduled.

E. g 

```
   LocalNotifications.schedule([{
    id: 1,
    title: 'The first title',
    body: 'The first  body',
    ticker: 'The ticker',
    badge: 1,
    sound: "sound1", 
    at: new Date(new Date().getTime() + (20 * 1000)) 
  }]).then(
      function() {
        console.log("Notification scheduled 1");
      },
      function(error) {
        console.log("scheduling error: " + error);
      }
  );



    LocalNotifications.schedule([{
    id: 2,
    title: 'The second',
    body: 'The second body',
    ticker: 'The ticker',
    badge: 2,
    sound: "sound2",
    at: new Date(new Date().getTime() + (50 * 1000)) 
  }]).then(
      function() {
        console.log("Notification scheduled 2");
      },
      function(error) {
        console.log("scheduling error: " + error);
      }
  );

```

_The code above will set two notifications with custom sound **sound1.mp3** and **sound2.mp3**, both files are expected to be in the raw folder_

Cheers.

[files.zip](https://github.com/Obsessive/nativescript-custom-local-notifications/files/473635/files.zip)

**Comment by Obsessive** [comment]
repo updated. 

Thanks ben !!
We wanted to do this for a while now.. but the temporary solution was enough for our project.
really appreciate the contribution :)

**Comment by b3nnee** [comment]
Hello,You are really welcome.Cheers,
